source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.3"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 5.2.3"
# Use postgresql as the database for Active Record
gem "pg", ">= 0.18", "< 2.0"
# Use Puma as the app server
gem "puma", "~> 3.11"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.5"
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem "friendly_id", "~> 5.2"

# Logging and exception tracking
gem "sentry-raven"

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem "web-console", ">= 3.3.0"
  gem "listen", ">= 3.0.5", "< 3.2"
end

group :development, :test do
  # Style guide enforcement
  gem "standard"
  # Debugging
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]

  # Integrations with Rails
  gem "dotenv-rails", "~> 2.7"
  gem "rspec-rails", "~> 3.8"

  # Builders for data
  gem "factory_bot_rails", "~> 5.0"
  gem "ffaker", "~> 2.9"

  # Assertions against rails
  gem "shoulda-matchers", "~> 4.1"

  # Fakes for external dependencies
  gem "coruro-ruby", "~> 0.6"

  # Assertions against web/mail interfaces
  gem "capybara", "~> 3.20"
  gem "email_spec", "~> 2.2"
  gem "selenium-webdriver", "~> 3.142"
  gem "webdrivers", "~> 4.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
